version: '2'

services:

  php-fpm:
    build:
      context: ./php-fpm
      dockerfile: Dockerfile-70
    volumes_from:
      - application
    expose:
      - "9000"
    links:
      - workspace

  application:
    build: ./application
    volumes:
      - ../:/var/www/codeigniter

  data:
    build: ./data
    volumes:
      - /var/lib/mysql
      - /var/lib/mariadb
      - /var/lib/redis

  nginx:
    build: ./nginx
    volumes_from:
      - application
    volumes:
      - ./logs/nginx/:/var/log/nginx
    ports:
      - "80:80"
      - "443:443"
    links:
      - php-fpm

  mysql:
    build: ./mysql
    volumes_from:
      - data
    ports:
      - "3306:3306"
    environment:
      MYSQL_DATABASE: ci
      MYSQL_USER: ci
      MYSQL_PASSWORD: secret
      MYSQL_ROOT_PASSWORD: root

  # mariadb:
  #   build: ./mariadb
  #   volumes_from:
  #     - data
  #   ports:
  #     - "3306:3306"
  #   environment:
  #     MYSQL_DATABASE: ci
  #     MYSQL_USER: ci
  #     MYSQL_PASSWORD: secret
  #     MYSQL_ROOT_PASSWORD: root

  redis:
    build: ./redis
    volumes_from:
      - data
    ports:
      - "6379:6379"

  workspace:
    build: ./workspace
    volumes_from:
      - application
    tty: true
